export type Product = {
  slug: string;
  name: string;
  category: "CRM" | "Project Management";
  shortDescription: string;
  pricingTier: "Free" | "Freemium" | "Paid";
  affiliatePlaceholderUrl: string;
};

export const products: Product[] = [
  // CRM
  {
    slug: "hubspot",
    name: "HubSpot",
    category: "CRM",
    shortDescription: "A powerful, easy-to-use CRM for scaling businesses.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/hubspot",
  },
  {
    slug: "salesforce",
    name: "Salesforce",
    category: "CRM",
    shortDescription: "The world's #1 CRM platform for businesses of all sizes.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/salesforce",
  },
  {
    slug: "pipedrive",
    name: "Pipedrive",
    category: "CRM",
    shortDescription: "The first CRM designed by salespeople, for salespeople.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/pipedrive",
  },
  {
    slug: "zoho-crm",
    name: "Zoho CRM",
    category: "CRM",
    shortDescription: "A robust CRM with a wide range of features and integrations.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/zoho-crm",
  },
  {
    slug: "monday-crm",
    name: "Monday CRM",
    category: "CRM",
    shortDescription: "A customizable CRM built on the monday.com Work OS.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/monday-crm",
  },
  {
    slug: "freshsales",
    name: "Freshsales",
    category: "CRM",
    shortDescription: "AI-powered CRM for high-growth sales teams.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/freshsales",
  },
  {
    slug: "copper",
    name: "Copper",
    category: "CRM",
    shortDescription: "The CRM for Google Workspace users.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/copper",
  },
  {
    slug: "insightly",
    name: "Insightly",
    category: "CRM",
    shortDescription: "CRM with built-in project management for growing teams.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/insightly",
  },
  {
    slug: "keap",
    name: "Keap",
    category: "CRM",
    shortDescription: "CRM, sales, and marketing automation for small businesses.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/keap",
  },
  {
    slug: "activecampaign",
    name: "ActiveCampaign",
    category: "CRM",
    shortDescription: "Automated sales and marketing CRM.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/activecampaign",
  },
  {
    slug: "close",
    name: "Close",
    category: "CRM",
    shortDescription: "CRM for high-volume sales teams who want to close more deals.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/close",
  },
  {
    slug: "capsule",
    name: "Capsule",
    category: "CRM",
    shortDescription: "The smart simple online CRM.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/capsule",
  },
  {
    slug: "nimble",
    name: "Nimble",
    category: "CRM",
    shortDescription: "Social CRM for small business teams.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/nimble",
  },
  {
    slug: "less-annoying-crm",
    name: "Less Annoying CRM",
    category: "CRM",
    shortDescription: "A simple CRM built for small businesses.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/less-annoying-crm",
  },
  {
    slug: "nutshell",
    name: "Nutshell",
    category: "CRM",
    shortDescription: "The CRM that helps sales teams close more deals.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/nutshell",
  },

  // Project Management
  {
    slug: "asana",
    name: "Asana",
    category: "Project Management",
    shortDescription: "Manage your team's work, projects, and tasks online.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/asana",
  },
  {
    slug: "trello",
    name: "Trello",
    category: "Project Management",
    shortDescription: "Collaborate on projects from anywhere with Trello.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/trello",
  },
  {
    slug: "clickup",
    name: "ClickUp",
    category: "Project Management",
    shortDescription: "The all-in-one productivity platform.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/clickup",
  },
  {
    slug: "monday-pm",
    name: "Monday.com",
    category: "Project Management",
    shortDescription: "Work without limits with monday.com.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/monday-pm",
  },
  {
    slug: "notion",
    name: "Notion",
    category: "Project Management",
    shortDescription: "The all-in-one workspace for notes, tasks, and wikis.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/notion",
  },
  {
    slug: "jira",
    name: "Jira",
    category: "Project Management",
    shortDescription: "The #1 software development tool used by agile teams.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/jira",
  },
  {
    slug: "wrike",
    name: "Wrike",
    category: "Project Management",
    shortDescription: "Collaborative work management for high-performance teams.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/wrike",
  },
  {
    slug: "basecamp",
    name: "Basecamp",
    category: "Project Management",
    shortDescription: "The simple way to manage projects and teams.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/basecamp",
  },
  {
    slug: "teamwork",
    name: "Teamwork",
    category: "Project Management",
    shortDescription: "Project management software built for client work.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/teamwork",
  },
  {
    slug: "smartsheet",
    name: "Smartsheet",
    category: "Project Management",
    shortDescription: "Work execution platform for enterprises.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/smartsheet",
  },
  {
    slug: "airtable",
    name: "Airtable",
    category: "Project Management",
    shortDescription: "The platform for building powerful business apps.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/airtable",
  },
  {
    slug: "todoist",
    name: "Todoist",
    category: "Project Management",
    shortDescription: "The world's #1 to-do list and task manager.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/todoist",
  },
  {
    slug: "microsoft-project",
    name: "Microsoft Project",
    category: "Project Management",
    shortDescription: "Project management software by Microsoft.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/microsoft-project",
  },
  {
    slug: "paymo",
    name: "Paymo",
    category: "Project Management",
    shortDescription: "Work management and time tracking for teams.",
    pricingTier: "Freemium",
    affiliatePlaceholderUrl: "https://stackduel.com/go/paymo",
  },
  {
    slug: "proofhub",
    name: "ProofHub",
    category: "Project Management",
    shortDescription: "All-in-one project planning software.",
    pricingTier: "Paid",
    affiliatePlaceholderUrl: "https://stackduel.com/go/proofhub",
  },
];
